// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mdmhvlngucgbppwkzwcd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1kbWh2bG5ndWNnYnBwd2t6d2NkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwODIzNTQsImV4cCI6MjA3MzY1ODM1NH0.8wfVAWhv4u7JUHCzFoinL-d-K5ywtUpa7d5CYryB0j0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});